const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let T=localStorage.mira||'',page='brief',pid=null,user=null,es=null,hs=false;
const PAGES={brief:'Intelligence brief',products:'Products',feed:'Live feed',ask:'Ask MIRA',sources:'Sources & changes'};
async function api(p,d){const r=await fetch(p,{method:d?'POST':'GET',body:d?JSON.stringify(d):undefined,headers:{'Content-Type':'application/json',...(T&&{Authorization:'Bearer '+T})}});const x=await r.json().catch(()=>({}));if(r.status==401&&!p.includes('log')&&!p.includes('reg')){out();throw Error('Session expired')}if(!r.ok)throw Error(x.error||'Request failed');return x}
const toast=t=>{const e=$('#toast');e.textContent=t;e.style.display='block';setTimeout(()=>e.style.display='none',2800)};
async function auth(kind){try{const r=await api('/api/'+kind,{email:$('#em').value,password:$('#pw').value,name:$('#em').value.split('@')[0]});T=r.token;localStorage.mira=T;boot()}catch(e){$('#err').textContent=e.message}}
function out(){T='';localStorage.removeItem('mira');es&&es.close();$('#shell').hidden=true;$('#auth').hidden=false}
async function boot(){try{const me=await api('/api/me');if(!me.user)throw 0;user=me.user;hs=me.hindsight}catch(e){return out()}
 $('#auth').hidden=true;$('#shell').hidden=false;$('#nav').innerHTML=Object.entries(PAGES).map(([k,v])=>`<button data-p="${k}">${v}</button>`).join('');
 $('#mem').innerHTML=hs?'<b style="color:var(--g)">● Hindsight memory on</b><br>Every sync &amp; question is remembered':'<b style="color:var(--y)">● Hindsight not set</b><br>Set HINDSIGHT_* env vars for long-term memory';
 stream();go('brief')}
function go(p,id){page=p;pid=id||null;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('on',b.dataset.p===p||(p==='product'&&b.dataset.p==='products')));$('#ttl').textContent=p==='product'?'Product deep-dive':PAGES[p];draw()}
async function draw(q){if(!q)$('#c').innerHTML='<div class="empty">Loading…</div>';try{$('#c').innerHTML=await VIEW[page]()}catch(e){$('#c').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-p]');if(b&&b.closest('#nav'))go(b.dataset.p);const g=e.target.closest('[data-go]');if(g)go('product',+g.dataset.go)});
$('#go').onclick=()=>auth('login');$('#reg').onclick=()=>auth('register');$('#out').onclick=out;$('#pw').onkeydown=e=>e.key==='Enter'&&auth('login');

// ---- charts ----
function trend(revs,evs){const pts=revs.filter(r=>r.score!=null).map(r=>({t:+new Date(r.review_date),y:r.score}));if(pts.length<3)return'<div class="muted">Not enough scored feedback for a trend yet.</div>';
 const wk=6048e5,b={};pts.forEach(p=>{const k=Math.floor(p.t/wk);(b[k]=b[k]||[]).push(p.y)});const s=Object.entries(b).sort((a,c)=>a[0]-c[0]).map(([k,v])=>({t:k*wk,y:v.reduce((a,c)=>a+c,0)/v.length,n:v.length}));
 const evt=evs.map(e=>({t:+new Date(e.occurred_at.slice(0,10)),title:e.title}));const ts=[...s.map(x=>x.t),...evt.map(x=>x.t)],t0=Math.min(...ts),t1=Math.max(...ts,t0+wk),W=760,H=230,X=t=>40+(t-t0)/(t1-t0||1)*(W-60),Y=v=>15+(1-(v+1)/2)*(H-45);
 let svg=`<svg viewBox="0 0 ${W} ${H}" width="100%"><line x1="40" x2="${W-20}" y1="${Y(0)}" y2="${Y(0)}" stroke="#232838"/><text x="4" y="${Y(1)+4}">+1</text><text x="4" y="${Y(0)+4}">0</text><text x="4" y="${Y(-1)+4}">−1</text>`;
 evt.forEach((e,i)=>svg+=`<line x1="${X(e.t)}" x2="${X(e.t)}" y1="8" y2="${H-25}" stroke="#7c8cff" stroke-dasharray="4"/><text x="${X(e.t)+4}" y="${16+i%3*11}" style="fill:#7c8cff">${esc(e.title.slice(0,32))}</text>`);
 svg+=`<polyline fill="none" stroke="#3ddc97" stroke-width="2.5" points="${s.map(p=>X(p.t)+','+Y(p.y)).join(' ')}"/>`+s.map(p=>`<circle cx="${X(p.t)}" cy="${Y(p.y)}" r="${2+Math.min(4,p.n/4)}" fill="${p.y<-.2?'#ff6b6b':p.y>.2?'#3ddc97':'#ffc857'}"><title>${new Date(p.t).toDateString()} · ${p.y.toFixed(2)} · ${p.n} items</title></circle>`).join('');
 return svg+`<text x="40" y="${H-6}">${new Date(t0).toLocaleDateString()}</text><text x="${W-90}" y="${H-6}">${new Date(t1).toLocaleDateString()}</text></svg>`}
function stack(themes){const m={};themes.forEach(t=>{(m[t.theme]=m[t.theme]||{positive:0,negative:0,mixed:0,n:0})[t.sentiment]+=t.n;m[t.theme].n+=t.n});const top=Object.entries(m).sort((a,b)=>b[1].n-a[1].n).slice(0,8),mx=top[0]?.[1].n||1;
 return top.map(([k,v])=>`<div class="row"><div class="l">${esc(k)}</div><div class="bar" style="width:${v.n/mx*100}%;flex:none;min-width:40px"><i class="pos" style="width:${v.positive/v.n*100}%"></i><i class="mix" style="width:${v.mixed/v.n*100}%"></i><i class="neg" style="width:${v.negative/v.n*100}%"></i></div><span class="muted">${v.n}</span></div>`).join('')||'<div class="muted">No themes yet</div>'}
const onboard=()=>`<div class="card hero empty"><h1>Collecting live customer feedback…</h1><p>MIRA is discovering the apps and pulling real reviews from the App Store &amp; Hacker News right now. This page refreshes itself — give it about a minute.</p><div class="steps"><div class="card"><b>1 · Track</b><br><span class="muted">Add a product with an App Store id, Reddit/HN query, a product page URL or Amazon ASIN.</span></div><div class="card"><b>2 · Log changes</b><br><span class="muted">Releases from the App Store are auto-detected; log firmware, price or policy changes yourself.</span></div><div class="card"><b>3 · Read the brief</b><br><span class="muted">Spikes, sentiment shifts and “did the fix work?” verdicts appear here.</span></div></div><br><button class="pri" onclick="go('sources')">Add sources →</button></div>`;

const VIEW={
async brief(){const [s,im,bu,th,ch,rv,ev]=await Promise.all([api('/api/summary'),api('/api/impact'),api('/api/bursts'),api('/api/themes'),api('/api/channels'),api('/api/reviews?limit=200'),api('/api/timeline')]);if(!s.products)return onboard();
 const sig=[...bu.map(b=>({c:b.neg_share>.5?'neg':'mix',h:`“${b.theme}” is ${b.signal==='new'?'newly appearing':'spiking'}`,d:`${b.recent} mentions in 14 days${b.z?` · z=${b.z}`:''} · ${Math.round(b.neg_share*100)}% negative`})),
 ...im.filter(i=>i.verdict!=='insufficient data yet').map(i=>({c:i.verdict.includes('improved')?'pos':i.verdict.includes('regressed')?'neg':'mix',h:`${i.change} → ${i.verdict}`,d:`${i.product} · sentiment Δ ${i.sentiment_delta} (p=${i.p_value}) · ${i.n_before} before / ${i.n_after} after`}))];
 const chn={};ch.forEach(c=>chn[c.channel]=(chn[c.channel]||0)+c.n);const cm=Math.max(...Object.values(chn),1);
 return`<div class="grid g4"><div class="card kpi"><b>${s.reviews}</b><span>feedback items</span></div><div class="card kpi"><b>${s.products}</b><span>products tracked</span></div><div class="card kpi"><b>${s.channels}</b><span>channels</span></div><div class="card kpi"><b>${bu.length}</b><span>active signals</span></div></div>
 <div class="grid g2"><div class="card"><h3>Sentiment over time · dashed = product changes</h3>${trend(rv,ev.filter(e=>e.kind==='product_change'))}</div><div class="card"><h3>Signals MIRA found</h3>${sig.map(x=>`<div class="sig"><span class="dot ${x.c}"></span><div><b>${esc(x.h)}</b><br><small>${esc(x.d)}</small></div></div>`).join('')||'<div class="muted">No statistically notable shifts yet — MIRA needs a few weeks of baseline to call a spike.</div>'}</div></div>
 <div class="grid g2"><div class="card"><h3>What people talk about · <span style="color:var(--g)">pos</span> / <span style="color:var(--y)">mixed</span> / <span style="color:var(--r)">neg</span></h3>${stack(th)}</div><div class="card"><h3>Channel mix</h3>${Object.entries(chn).map(([k,v])=>`<div class="row"><div class="l">${esc(k)}</div><div class="bar"><i style="width:${v/cm*100}%;background:var(--a)"></i></div><span class="muted">${v}</span></div>`).join('')}</div></div>`},
async products(){const p=await api('/api/products');return p.length?`<div class="grid g4">${p.map(x=>`<div class="card" style="cursor:pointer" data-go="${x.id}">${x.image&&x.image.startsWith('http')?`<img src="${esc(x.image)}" width="48" height="48" style="border-radius:12px;float:right">`:''}<b>${esc(x.name)}</b><br><span class="muted">${esc(x.category)}${x.rating?` · ${(+x.rating).toFixed(1)}★ store rating`:''}</span><br><br><span class="tag" style="margin:0">Deep-dive →</span></div>`).join('')}</div>`:onboard()},
async product(){const [ps,rv,ev,th,im,bu]=await Promise.all([api('/api/products'),api('/api/reviews?limit=200&product_id='+pid),api('/api/timeline?product_id='+pid),api('/api/themes?product_id='+pid),api('/api/impact?product_id='+pid),api('/api/bursts?product_id='+pid)]);const p=ps.find(x=>x.id==pid)||{};
 return`<div class="card hero"><h1>${esc(p.name)}</h1><span class="muted">${rv.length} recent items · ${bu.length} live signals</span></div><div class="card"><h3>Sentiment vs. product changes</h3>${trend(rv,ev.filter(e=>e.kind==='product_change'))}</div><div class="grid g2"><div class="card"><h3>Themes</h3>${stack(th)}</div><div class="card"><h3>Change impact</h3>${im.map(i=>`<div class="sig"><span class="dot ${i.verdict.includes('improved')?'pos':i.verdict.includes('regressed')?'neg':'mix'}"></span><div><b>${esc(i.change)}</b><br><small>${esc(i.verdict)} · Δ ${i.sentiment_delta??'—'} · p=${i.p_value??'—'}<br>target: ${esc(i.target_aspect)}${i.aspect_delta!=null?' · aspect Δ '+i.aspect_delta:''}</small></div></div>`).join('')||'<div class="muted">No changes logged for this product.</div>'}</div></div>
 <div class="card"><h3>Latest evidence</h3>${rv.slice(0,12).map(feedRow).join('')}</div>`},
async feed(){const f=await api('/api/feed?limit=60');return`<div class="card" id="feedbox">${f.map(feedRow).join('')||'<div class="empty">Nothing ingested yet.</div>'}</div>`},
async ask(){return`<div class="card"><h3>Ask across all channels and time (Hindsight recall + reflect)</h3><input id="q" placeholder="Did the last update fix battery complaints? What's new this week?"><button class="pri" onclick="ask()">Ask MIRA</button><div id="ans" style="margin-top:16px"></div></div>`},
async sources(){const [cn,ad,ps]=await Promise.all([api('/api/connectors'),api('/api/adapters'),api('/api/products')]);
 return`<div class="grid g2"><div class="card"><h3>Track a product</h3><input id="tn" placeholder="Product name"><input id="tc" placeholder="Category">${Object.entries(ad).map(([k,v])=>`<input data-src="${k}" placeholder="${k}: ${esc(v)}">`).join('')}<button class="pri" onclick="track()">Track &amp; sync now</button></div>
 <div><div class="card"><h3>Log a product change</h3><select id="cp">${ps.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select><input id="ct" placeholder="Firmware 2.4.1 — battery fix"><input id="cd" type="date"><button class="ghost" onclick="chg()">Save change</button></div><br>
 <div class="card"><h3>Live sources</h3>${cn.map(c=>`<div class="sig"><span class="dot ${c.status==='ok'?'pos':c.status==='error'?'neg':'mix'}"></span><div style="flex:1"><b>${esc(c.name)}</b><br><small>${esc(c.detail)}</small></div><button class="ghost" onclick="sync(${c.id})">Sync</button></div>`).join('')||'<div class="muted">No sources yet.</div>'}</div></div></div>`}};
const feedRow=x=>`<div class="feed" data-p2><span class="dot ${x.sentiment==='positive'?'pos':x.sentiment==='negative'?'neg':'mix'}" style="display:inline-block"></span> <b>${esc(x.product_name||'')}</b><span class="tag">${esc(x.channel)}</span><span class="tag">${esc(x.theme)}</span>${x.rating?`<span class="tag">${x.rating}★</span>`:''}<br><span class="muted">${esc((x.title?x.title+' — ':'')+(x.body||'').slice(0,220))}</span> <small class="muted">${esc(x.review_date||'')}</small></div>`;
async function ask(){$('#ans').innerHTML='Thinking…';try{const r=await api('/api/ask',{question:$('#q').value});$('#ans').innerHTML=`<div>${esc(r.answer).replace(/\*\*(.+?)\*\*/g,'<b>$1</b>').replace(/\n/g,'<br>')}</div><br><div class="muted">${esc(r.memory_status)}</div><h3 style="margin-top:16px">Evidence</h3>${(r.evidence||[]).map(feedRow).join('')}`}catch(e){$('#ans').textContent=e.message}}
async function track(){const sources=[...document.querySelectorAll('[data-src]')].filter(i=>i.value.trim()).map(i=>({kind:i.dataset.src,ref:i.value}));if(!$('#tn').value||!sources.length)return toast('Name and one source needed');await api('/api/track',{name:$('#tn').value,category:$('#tc').value,sources});toast('Tracking — first sync running');setTimeout(()=>go('brief'),5000)}
async function sync(id){toast('Syncing…');const r=await api('/api/sources/sync',{id});toast(r.ok?`+${r.added} new`:'Failed: '+r.error);draw()}
async function chg(){await api('/api/changes',{product_id:+$('#cp').value,title:$('#ct').value,date:$('#cd').value});toast('Logged');draw()}
function stream(){es&&es.close();es=new EventSource('/api/stream');es.addEventListener('hello',()=>{$('#live').textContent='live';$('#live').className='pill on'});es.onerror=()=>{$('#live').textContent='reconnecting';$('#live').className='pill'};
 es.addEventListener('feedback',e=>{const x=JSON.parse(e.data);if(page==='feed'&&$('#feedbox'))$('#feedbox').insertAdjacentHTML('afterbegin',feedRow(x).replace('class="feed"','class="feed new"'));else if(page==='brief')toast('New: '+x.theme+' ('+x.sentiment+')')})}
setInterval(()=>{if(!$('#shell').hidden&&['brief','products'].includes(page))draw(true)},30000);boot();
